tag @s remove tnt_display_black_hole_tnt
tag @s remove tnt_display_base_tnt
tag @s remove tnt_display_black_colored_tnt
tag @s remove tnt_display_blue_colored_tnt
tag @s remove tnt_display_brown_colored_tnt
tag @s remove tnt_display_cyan_colored_tnt
tag @s remove tnt_display_gray_colored_tnt
tag @s remove tnt_display_green_colored_tnt
tag @s remove tnt_display_light_blue_colored_tnt
tag @s remove tnt_display_light_gray_colored_tnt
tag @s remove tnt_display_lime_colored_tnt
tag @s remove tnt_display_magenta_colored_tnt
tag @s remove tnt_display_orange_colored_tnt
tag @s remove tnt_display_pink_colored_tnt
tag @s remove tnt_display_purple_colored_tnt
tag @s remove tnt_display_red_colored_tnt
tag @s remove tnt_display_white_colored_tnt
tag @s remove tnt_display_yellow_colored_tnt
tag @s remove tnt_display_arctic_tnt
tag @s remove tnt_display_big_bertha_tnt
tag @s remove tnt_display_blast_tnt
tag @s remove tnt_display_blaze_tnt
tag @s remove tnt_display_fireball_tnt
tag @s remove tnt_display_fish_tnt
tag @s remove tnt_display_galaxy_tnt
tag @s remove tnt_display_lightning_tnt
tag @s remove tnt_display_mega_tnt
tag @s remove tnt_display_party_tnt
tag @s remove tnt_display_potion_tnt
tag @s remove tnt_display_scatter_tnt
tag @s remove tnt_display_sticky_tnt
tag @s remove tnt_display_super_tnt
tag @s remove tnt_display_tornado_tnt
tag @s remove tnt_display_ultra_tnt
tag @s remove tnt_display_wither_tnt
tag @s remove tnt_display_axolotl_mob_tnt
tag @s remove tnt_display_bat_mob_tnt
tag @s remove tnt_display_cat_mob_tnt
tag @s remove tnt_display_chicken_mob_tnt
tag @s remove tnt_display_cow_mob_tnt
tag @s remove tnt_display_fox_mob_tnt
tag @s remove tnt_display_parrot_mob_tnt
tag @s remove tnt_display_pig_mob_tnt
tag @s remove tnt_display_polar_bear_mob_tnt
tag @s remove tnt_display_rabbit_mob_tnt
tag @s remove tnt_display_blessed_tnt
tag @s remove tnt_display_butterfly_tnt
tag @s remove tnt_display_circle_tnt
tag @s remove tnt_display_dinnerbone_tnt
tag @s remove tnt_display_dynamite_tnt
tag @s remove tnt_display_ender_tnt
tag @s remove tnt_display_equaliser_tnt
tag @s remove tnt_display_gravitational_tnt
tag @s remove tnt_display_infinity_tnt
tag @s remove tnt_display_magic_tnt
tag @s remove tnt_display_magnet_tnt
tag @s remove tnt_display_miners_tnt
tag @s remove tnt_display_napalm_tnt
tag @s remove tnt_display_patient_zero_tnt
tag @s remove tnt_display_device_crasher_tnt
tag @s remove tnt_display_portal_tnt
tag @s remove tnt_display_rainbow_tnt
tag @s remove tnt_display_shulker_tnt
tag @s remove tnt_display_black_smoke_tnt
tag @s remove tnt_display_split_tnt
tag @s remove tnt_display_sponge_tnt
tag @s remove tnt_display_wet_sponge_tnt
tag @s remove tnt_display_time_slower_tnt
tag @s remove tnt_display_troll_tnt
tag @s remove tnt_display_void_eater_tnt
tag @s remove tnt_display_world_ender_tnt
tag @s remove tnt_display_blue_smoke_tnt
tag @s remove tnt_display_brown_smoke_tnt
tag @s remove tnt_display_cyan_smoke_tnt
tag @s remove tnt_display_dark_green_smoke_tnt
tag @s remove tnt_display_gray_smoke_tnt
tag @s remove tnt_display_light_blue_smoke_tnt
tag @s remove tnt_display_light_gray_smoke_tnt
tag @s remove tnt_display_lime_smoke_tnt
tag @s remove tnt_display_magenta_smoke_tnt
tag @s remove tnt_display_orange_smoke_tnt
tag @s remove tnt_display_pink_smoke_tnt
tag @s remove tnt_display_purple_smoke_tnt
tag @s remove tnt_display_red_smoke_tnt
tag @s remove tnt_display_white_smoke_tnt
tag @s remove tnt_display_yellow_smoke_tnt
tag @s remove tnt_display_doomsday_tnt
tag @s remove tnt_display_lucky_tnt