structure load doomsday:str_1 ~-47 ~-48 ~-50
structure load doomsday:str_2 ~ ~-48 ~-50
structure load doomsday:str_3 ~-47 ~-48 ~
structure load doomsday:str_4 ~ ~-48 ~

execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-0 ~-50
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load doomsday:str_2 ~ ~-0 ~-50
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-0 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load doomsday:str_4 ~ ~-0 ~
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-1 ~-50
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load doomsday:str_2 ~ ~-1 ~-50
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load doomsday:str_4 ~ ~-1 ~
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-2 ~-50
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load doomsday:str_2 ~ ~-2 ~-50
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-2 ~
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load doomsday:str_4 ~ ~-2 ~
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-3 ~-50
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load doomsday:str_2 ~ ~-3 ~-50
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-3 ~
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load doomsday:str_4 ~ ~-3 ~
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-4 ~-50
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load doomsday:str_2 ~ ~-4 ~-50
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-4 ~
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load doomsday:str_4 ~ ~-4 ~
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-5 ~-50
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load doomsday:str_2 ~ ~-5 ~-50
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-5 ~
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load doomsday:str_4 ~ ~-5 ~
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-6 ~-50
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load doomsday:str_2 ~ ~-6 ~-50
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-6 ~
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load doomsday:str_4 ~ ~-6 ~
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-7 ~-50
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load doomsday:str_2 ~ ~-7 ~-50
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-7 ~
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load doomsday:str_4 ~ ~-7 ~
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-8 ~-50
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load doomsday:str_2 ~ ~-8 ~-50
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-8 ~
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load doomsday:str_4 ~ ~-8 ~
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-9 ~-50
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load doomsday:str_2 ~ ~-9 ~-50
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-9 ~
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load doomsday:str_4 ~ ~-9 ~
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-10 ~-50
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load doomsday:str_2 ~ ~-10 ~-50
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-10 ~
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load doomsday:str_4 ~ ~-10 ~
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-11 ~-50
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load doomsday:str_2 ~ ~-11 ~-50
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-11 ~
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load doomsday:str_4 ~ ~-11 ~
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-12 ~-50
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load doomsday:str_2 ~ ~-12 ~-50
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-12 ~
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load doomsday:str_4 ~ ~-12 ~
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-13 ~-50
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load doomsday:str_2 ~ ~-13 ~-50
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-13 ~
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load doomsday:str_4 ~ ~-13 ~
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-14 ~-50
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load doomsday:str_2 ~ ~-14 ~-50
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-14 ~
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load doomsday:str_4 ~ ~-14 ~
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-15 ~-50
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load doomsday:str_2 ~ ~-15 ~-50
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-15 ~
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load doomsday:str_4 ~ ~-15 ~
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-16 ~-50
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load doomsday:str_2 ~ ~-16 ~-50
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-16 ~
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load doomsday:str_4 ~ ~-16 ~
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-17 ~-50
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load doomsday:str_2 ~ ~-17 ~-50
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-17 ~
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load doomsday:str_4 ~ ~-17 ~
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-18 ~-50
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load doomsday:str_2 ~ ~-18 ~-50
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-18 ~
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load doomsday:str_4 ~ ~-18 ~
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-19 ~-50
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load doomsday:str_2 ~ ~-19 ~-50
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-19 ~
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load doomsday:str_4 ~ ~-19 ~
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-20 ~-50
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load doomsday:str_2 ~ ~-20 ~-50
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-20 ~
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load doomsday:str_4 ~ ~-20 ~
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-21 ~-50
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load doomsday:str_2 ~ ~-21 ~-50
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-21 ~
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load doomsday:str_4 ~ ~-21 ~
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-22 ~-50
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load doomsday:str_2 ~ ~-22 ~-50
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-22 ~
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load doomsday:str_4 ~ ~-22 ~
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-23 ~-50
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load doomsday:str_2 ~ ~-23 ~-50
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-23 ~
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load doomsday:str_4 ~ ~-23 ~
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-24 ~-50
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load doomsday:str_2 ~ ~-24 ~-50
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-24 ~
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load doomsday:str_4 ~ ~-24 ~
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-25 ~-50
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load doomsday:str_2 ~ ~-25 ~-50
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-25 ~
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load doomsday:str_4 ~ ~-25 ~
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-26 ~-50
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load doomsday:str_2 ~ ~-26 ~-50
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-26 ~
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load doomsday:str_4 ~ ~-26 ~
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-27 ~-50
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load doomsday:str_2 ~ ~-27 ~-50
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-27 ~
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load doomsday:str_4 ~ ~-27 ~
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-28 ~-50
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load doomsday:str_2 ~ ~-28 ~-50
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-28 ~
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load doomsday:str_4 ~ ~-28 ~
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-29 ~-50
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load doomsday:str_2 ~ ~-29 ~-50
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-29 ~
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load doomsday:str_4 ~ ~-29 ~
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-30 ~-50
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load doomsday:str_2 ~ ~-30 ~-50
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-30 ~
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load doomsday:str_4 ~ ~-30 ~
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-31 ~-50
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load doomsday:str_2 ~ ~-31 ~-50
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-31 ~
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load doomsday:str_4 ~ ~-31 ~
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-32 ~-50
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load doomsday:str_2 ~ ~-32 ~-50
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-32 ~
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load doomsday:str_4 ~ ~-32 ~
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-33 ~-50
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load doomsday:str_2 ~ ~-33 ~-50
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-33 ~
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load doomsday:str_4 ~ ~-33 ~
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-34 ~-50
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load doomsday:str_2 ~ ~-34 ~-50
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-34 ~
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load doomsday:str_4 ~ ~-34 ~
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-35 ~-50
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load doomsday:str_2 ~ ~-35 ~-50
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-35 ~
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load doomsday:str_4 ~ ~-35 ~
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-36 ~-50
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load doomsday:str_2 ~ ~-36 ~-50
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-36 ~
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load doomsday:str_4 ~ ~-36 ~
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-37 ~-50
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load doomsday:str_2 ~ ~-37 ~-50
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-37 ~
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load doomsday:str_4 ~ ~-37 ~
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-38 ~-50
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load doomsday:str_2 ~ ~-38 ~-50
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-38 ~
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load doomsday:str_4 ~ ~-38 ~
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-39 ~-50
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load doomsday:str_2 ~ ~-39 ~-50
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-39 ~
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load doomsday:str_4 ~ ~-39 ~
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-40 ~-50
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load doomsday:str_2 ~ ~-40 ~-50
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-40 ~
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load doomsday:str_4 ~ ~-40 ~
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-41 ~-50
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load doomsday:str_2 ~ ~-41 ~-50
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-41 ~
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load doomsday:str_4 ~ ~-41 ~
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-42 ~-50
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load doomsday:str_2 ~ ~-42 ~-50
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-42 ~
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load doomsday:str_4 ~ ~-42 ~
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-43 ~-50
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load doomsday:str_2 ~ ~-43 ~-50
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-43 ~
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load doomsday:str_4 ~ ~-43 ~
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-44 ~-50
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load doomsday:str_2 ~ ~-44 ~-50
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-44 ~
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load doomsday:str_4 ~ ~-44 ~
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-45 ~-50
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load doomsday:str_2 ~ ~-45 ~-50
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-45 ~
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load doomsday:str_4 ~ ~-45 ~
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-46 ~-50
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load doomsday:str_2 ~ ~-46 ~-50
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-46 ~
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load doomsday:str_4 ~ ~-46 ~
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load doomsday:str_1 ~-47 ~-47 ~-50
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load doomsday:str_2 ~ ~-47 ~-50
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load doomsday:str_3 ~-47 ~-47 ~
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load doomsday:str_4 ~ ~-47 ~