summon sndbx:mushroom_cloud ~ ~-48 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-0 ~
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-1 ~
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-2 ~
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-3 ~
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-4 ~
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-5 ~
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-6 ~
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-7 ~
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-8 ~
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-9 ~
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-10 ~
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-11 ~
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-12 ~
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-13 ~
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-14 ~
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-15 ~
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-16 ~
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-17 ~
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-18 ~
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-19 ~
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-20 ~
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-21 ~
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-22 ~
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-23 ~
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-24 ~
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-25 ~
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-26 ~
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-27 ~
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-28 ~
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-29 ~
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-30 ~
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-31 ~
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-32 ~
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-33 ~
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-34 ~
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-35 ~
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-36 ~
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-37 ~
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-38 ~
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-39 ~
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-40 ~
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-41 ~
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-42 ~
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-43 ~
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-44 ~
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-45 ~
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-46 ~
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 summon sndbx:mushroom_cloud ~ ~-47 ~