execute @s ~~~ detect ~~-4~ bedrock -1 event entity @s sndbx:despawn_explode
execute @s ~~~ detect ~~-3~ bedrock -1 event entity @s sndbx:despawn_explode
execute @s ~~~ detect ~~-2~ bedrock -1 event entity @s sndbx:despawn_explode
execute @s ~~~ detect ~~-1~ bedrock -1 event entity @s sndbx:despawn_explode

execute @e[type=item,x=~-5,y=~,z=~-5,dx=5,dy=5,dz=5] ~~~ tp ^^^0.01 facing @e[family=miners_tnt,c=1]

execute @s ~~~ detect ~-5 ~-1 ~5 stone -1 setblock ~-5 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~5 stone -1 setblock ~5 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~5 stone -1 setblock ~-4 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~5 stone -1 setblock ~4 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~5 stone -1 setblock ~-3 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~5 stone -1 setblock ~3 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~5 stone -1 setblock ~-2 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~5 stone -1 setblock ~2 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~5 stone -1 setblock ~-1 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~5 stone -1 setblock ~1 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~5 stone -1 setblock ~ ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~5 stone -1 setblock ~ ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~4 stone -1 setblock ~-5 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~4 stone -1 setblock ~5 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~4 stone -1 setblock ~-4 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~4 stone -1 setblock ~4 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~4 stone -1 setblock ~-3 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~4 stone -1 setblock ~3 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~4 stone -1 setblock ~-2 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~4 stone -1 setblock ~2 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~4 stone -1 setblock ~-1 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~4 stone -1 setblock ~1 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~4 stone -1 setblock ~ ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~4 stone -1 setblock ~ ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~3 stone -1 setblock ~-5 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~3 stone -1 setblock ~5 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~3 stone -1 setblock ~-4 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~3 stone -1 setblock ~4 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~3 stone -1 setblock ~-3 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~3 stone -1 setblock ~3 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~3 stone -1 setblock ~-2 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~3 stone -1 setblock ~2 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~3 stone -1 setblock ~-1 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~3 stone -1 setblock ~1 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~3 stone -1 setblock ~ ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~3 stone -1 setblock ~ ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~2 stone -1 setblock ~-5 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~2 stone -1 setblock ~5 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~2 stone -1 setblock ~-4 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~2 stone -1 setblock ~4 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~2 stone -1 setblock ~-3 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~2 stone -1 setblock ~3 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~2 stone -1 setblock ~-2 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~2 stone -1 setblock ~2 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~2 stone -1 setblock ~-1 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~2 stone -1 setblock ~1 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~2 stone -1 setblock ~ ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~2 stone -1 setblock ~ ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~1 stone -1 setblock ~-5 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~1 stone -1 setblock ~5 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~1 stone -1 setblock ~-4 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~1 stone -1 setblock ~4 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~1 stone -1 setblock ~-3 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~1 stone -1 setblock ~3 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~1 stone -1 setblock ~-2 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~1 stone -1 setblock ~2 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~1 stone -1 setblock ~-1 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~1 stone -1 setblock ~1 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~1 stone -1 setblock ~ ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~1 stone -1 setblock ~ ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~ stone -1 setblock ~-5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~ stone -1 setblock ~5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~ stone -1 setblock ~-4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~ stone -1 setblock ~4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~ stone -1 setblock ~-3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~ stone -1 setblock ~3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~ stone -1 setblock ~-2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~ stone -1 setblock ~2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~ stone -1 setblock ~-1 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~ stone -1 setblock ~1 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~ ~-1 ~ stone -1 setblock ~ ~-1 ~ air 0 destroy
execute @s ~~~ detect ~ ~-1 ~ stone -1 setblock ~ ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-5 stone -1 setblock ~-5 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-5 stone -1 setblock ~5 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-5 stone -1 setblock ~-4 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-5 stone -1 setblock ~4 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-5 stone -1 setblock ~-3 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-5 stone -1 setblock ~3 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-5 stone -1 setblock ~-2 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-5 stone -1 setblock ~2 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-5 stone -1 setblock ~-1 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-5 stone -1 setblock ~1 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-5 stone -1 setblock ~ ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-5 stone -1 setblock ~ ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-4 stone -1 setblock ~-5 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-4 stone -1 setblock ~5 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-4 stone -1 setblock ~-4 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-4 stone -1 setblock ~4 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-4 stone -1 setblock ~-3 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-4 stone -1 setblock ~3 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-4 stone -1 setblock ~-2 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-4 stone -1 setblock ~2 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-4 stone -1 setblock ~-1 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-4 stone -1 setblock ~1 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-4 stone -1 setblock ~ ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-4 stone -1 setblock ~ ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-3 stone -1 setblock ~-5 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-3 stone -1 setblock ~5 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-3 stone -1 setblock ~-4 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-3 stone -1 setblock ~4 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-3 stone -1 setblock ~-3 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-3 stone -1 setblock ~3 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-3 stone -1 setblock ~-2 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-3 stone -1 setblock ~2 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-3 stone -1 setblock ~-1 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-3 stone -1 setblock ~1 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-3 stone -1 setblock ~ ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-3 stone -1 setblock ~ ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-2 stone -1 setblock ~-5 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-2 stone -1 setblock ~5 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-2 stone -1 setblock ~-4 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-2 stone -1 setblock ~4 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-2 stone -1 setblock ~-3 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-2 stone -1 setblock ~3 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-2 stone -1 setblock ~-2 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-2 stone -1 setblock ~2 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-2 stone -1 setblock ~-1 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-2 stone -1 setblock ~1 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-2 stone -1 setblock ~ ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-2 stone -1 setblock ~ ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-1 stone -1 setblock ~-5 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-1 stone -1 setblock ~5 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-1 stone -1 setblock ~-4 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-1 stone -1 setblock ~4 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-1 stone -1 setblock ~-3 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-1 stone -1 setblock ~3 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-1 stone -1 setblock ~-2 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-1 stone -1 setblock ~2 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-1 stone -1 setblock ~-1 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-1 stone -1 setblock ~1 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-1 stone -1 setblock ~ ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-1 stone -1 setblock ~ ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~ stone -1 setblock ~-5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~ stone -1 setblock ~5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~ stone -1 setblock ~-4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~ stone -1 setblock ~4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~ stone -1 setblock ~-3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~ stone -1 setblock ~3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~ stone -1 setblock ~-2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~ stone -1 setblock ~2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~ stone -1 setblock ~-1 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~ stone -1 setblock ~1 ~-1 ~ air 0 destroy

execute @s ~~~ detect ~-5 ~-1 ~5 dirt -1 setblock ~-5 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~5 dirt -1 setblock ~5 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~5 dirt -1 setblock ~-4 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~5 dirt -1 setblock ~4 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~5 dirt -1 setblock ~-3 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~5 dirt -1 setblock ~3 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~5 dirt -1 setblock ~-2 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~5 dirt -1 setblock ~2 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~5 dirt -1 setblock ~-1 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~5 dirt -1 setblock ~1 ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~5 dirt -1 setblock ~ ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~5 dirt -1 setblock ~ ~-1 ~5 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~4 dirt -1 setblock ~-5 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~4 dirt -1 setblock ~5 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~4 dirt -1 setblock ~-4 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~4 dirt -1 setblock ~4 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~4 dirt -1 setblock ~-3 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~4 dirt -1 setblock ~3 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~4 dirt -1 setblock ~-2 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~4 dirt -1 setblock ~2 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~4 dirt -1 setblock ~-1 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~4 dirt -1 setblock ~1 ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~4 dirt -1 setblock ~ ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~4 dirt -1 setblock ~ ~-1 ~4 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~3 dirt -1 setblock ~-5 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~3 dirt -1 setblock ~5 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~3 dirt -1 setblock ~-4 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~3 dirt -1 setblock ~4 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~3 dirt -1 setblock ~-3 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~3 dirt -1 setblock ~3 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~3 dirt -1 setblock ~-2 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~3 dirt -1 setblock ~2 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~3 dirt -1 setblock ~-1 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~3 dirt -1 setblock ~1 ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~3 dirt -1 setblock ~ ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~3 dirt -1 setblock ~ ~-1 ~3 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~2 dirt -1 setblock ~-5 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~2 dirt -1 setblock ~5 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~2 dirt -1 setblock ~-4 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~2 dirt -1 setblock ~4 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~2 dirt -1 setblock ~-3 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~2 dirt -1 setblock ~3 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~2 dirt -1 setblock ~-2 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~2 dirt -1 setblock ~2 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~2 dirt -1 setblock ~-1 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~2 dirt -1 setblock ~1 ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~2 dirt -1 setblock ~ ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~2 dirt -1 setblock ~ ~-1 ~2 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~1 dirt -1 setblock ~-5 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~1 dirt -1 setblock ~5 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~1 dirt -1 setblock ~-4 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~1 dirt -1 setblock ~4 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~1 dirt -1 setblock ~-3 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~1 dirt -1 setblock ~3 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~1 dirt -1 setblock ~-2 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~1 dirt -1 setblock ~2 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~1 dirt -1 setblock ~-1 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~1 dirt -1 setblock ~1 ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~1 dirt -1 setblock ~ ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~1 dirt -1 setblock ~ ~-1 ~1 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~ dirt -1 setblock ~-5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~ dirt -1 setblock ~5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~ dirt -1 setblock ~-4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~ dirt -1 setblock ~4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~ dirt -1 setblock ~-3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~ dirt -1 setblock ~3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~ dirt -1 setblock ~-2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~ dirt -1 setblock ~2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~ dirt -1 setblock ~-1 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~ dirt -1 setblock ~1 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~ ~-1 ~ dirt -1 setblock ~ ~-1 ~ air 0 destroy
execute @s ~~~ detect ~ ~-1 ~ dirt -1 setblock ~ ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-5 dirt -1 setblock ~-5 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-5 dirt -1 setblock ~5 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-5 dirt -1 setblock ~-4 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-5 dirt -1 setblock ~4 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-5 dirt -1 setblock ~-3 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-5 dirt -1 setblock ~3 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-5 dirt -1 setblock ~-2 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-5 dirt -1 setblock ~2 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-5 dirt -1 setblock ~-1 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-5 dirt -1 setblock ~1 ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-5 dirt -1 setblock ~ ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-5 dirt -1 setblock ~ ~-1 ~-5 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-4 dirt -1 setblock ~-5 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-4 dirt -1 setblock ~5 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-4 dirt -1 setblock ~-4 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-4 dirt -1 setblock ~4 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-4 dirt -1 setblock ~-3 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-4 dirt -1 setblock ~3 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-4 dirt -1 setblock ~-2 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-4 dirt -1 setblock ~2 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-4 dirt -1 setblock ~-1 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-4 dirt -1 setblock ~1 ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-4 dirt -1 setblock ~ ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-4 dirt -1 setblock ~ ~-1 ~-4 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-3 dirt -1 setblock ~-5 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-3 dirt -1 setblock ~5 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-3 dirt -1 setblock ~-4 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-3 dirt -1 setblock ~4 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-3 dirt -1 setblock ~-3 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-3 dirt -1 setblock ~3 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-3 dirt -1 setblock ~-2 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-3 dirt -1 setblock ~2 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-3 dirt -1 setblock ~-1 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-3 dirt -1 setblock ~1 ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-3 dirt -1 setblock ~ ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-3 dirt -1 setblock ~ ~-1 ~-3 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-2 dirt -1 setblock ~-5 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-2 dirt -1 setblock ~5 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-2 dirt -1 setblock ~-4 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-2 dirt -1 setblock ~4 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-2 dirt -1 setblock ~-3 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-2 dirt -1 setblock ~3 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-2 dirt -1 setblock ~-2 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-2 dirt -1 setblock ~2 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-2 dirt -1 setblock ~-1 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-2 dirt -1 setblock ~1 ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-2 dirt -1 setblock ~ ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-2 dirt -1 setblock ~ ~-1 ~-2 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~-1 dirt -1 setblock ~-5 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~-1 dirt -1 setblock ~5 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~-1 dirt -1 setblock ~-4 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~-1 dirt -1 setblock ~4 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~-1 dirt -1 setblock ~-3 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~-1 dirt -1 setblock ~3 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~-1 dirt -1 setblock ~-2 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~-1 dirt -1 setblock ~2 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~-1 dirt -1 setblock ~-1 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~-1 dirt -1 setblock ~1 ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-1 dirt -1 setblock ~ ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~ ~-1 ~-1 dirt -1 setblock ~ ~-1 ~-1 air 0 destroy
execute @s ~~~ detect ~-5 ~-1 ~ dirt -1 setblock ~-5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~5 ~-1 ~ dirt -1 setblock ~5 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-4 ~-1 ~ dirt -1 setblock ~-4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~4 ~-1 ~ dirt -1 setblock ~4 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-3 ~-1 ~ dirt -1 setblock ~-3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~3 ~-1 ~ dirt -1 setblock ~3 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-2 ~-1 ~ dirt -1 setblock ~-2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~2 ~-1 ~ dirt -1 setblock ~2 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~-1 ~-1 ~ dirt -1 setblock ~-1 ~-1 ~ air 0 destroy
execute @s ~~~ detect ~1 ~-1 ~ dirt -1 setblock ~1 ~-1 ~ air 0 destroy

fill ~1~-1~1~-1~-1~-1 air 0 destroy
particle sndbx:dig_smoke ~~~
playsound random.explode @a ~~~