
structure load mystructure:doomsday_expl ~-81 ~-68 ~-82
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-67 ~-82
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-66 ~-82
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-65 ~-82
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-64 ~-82
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-63 ~-82
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-62 ~-82
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-61 ~-82
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-60 ~-82
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-59 ~-82
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-58 ~-82
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-57 ~-82
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-56 ~-82
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-55 ~-82
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-54 ~-82
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-53 ~-82
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-52 ~-82
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-51 ~-82
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-50 ~-82
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-49 ~-82
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-48 ~-82
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-47 ~-82
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-46 ~-82
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-45 ~-82
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-44 ~-82
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-43 ~-82
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-42 ~-82
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-41 ~-82
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-40 ~-82
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-39 ~-82
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-38 ~-82
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-37 ~-82
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-36 ~-82
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-35 ~-82
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-34 ~-82
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-33 ~-82
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-32 ~-82
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-31 ~-82
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-30 ~-82
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-29 ~-82
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-28 ~-82
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-27 ~-82
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-26 ~-82
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-25 ~-82
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-24 ~-82
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-23 ~-82
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-22 ~-82
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-21 ~-82
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-20 ~-82
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-19 ~-82
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-18 ~-82
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-17 ~-82
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-16 ~-82
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-15 ~-82
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-14 ~-82
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-13 ~-82
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-12 ~-82
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-11 ~-82
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-10 ~-82
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-9 ~-82
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-8 ~-82
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-7 ~-82
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-6 ~-82
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-5 ~-82
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-4 ~-82
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-3 ~-82
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-2 ~-82
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-1 ~-82

structure load mystructure:doomsday_expl ~ ~-68 ~
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-67 ~
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-66 ~
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-65 ~
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-64 ~
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-63 ~
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-62 ~
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-61 ~
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-60 ~
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-59 ~
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-58 ~
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-57 ~
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-56 ~
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-55 ~
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-54 ~
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-53 ~
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-52 ~
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-51 ~
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-50 ~
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-49 ~
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-48 ~
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-47 ~
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-46 ~
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-45 ~
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-44 ~
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-43 ~
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-42 ~
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-41 ~
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-40 ~
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-39 ~
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-38 ~
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-37 ~
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-36 ~
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-35 ~
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-34 ~
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-33 ~
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-32 ~
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-31 ~
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-30 ~
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-29 ~
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-28 ~
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-27 ~
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-26 ~
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-25 ~
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-24 ~
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-23 ~
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-22 ~
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-21 ~
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-20 ~
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-19 ~
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-18 ~
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-17 ~
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-16 ~
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-15 ~
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-14 ~
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-13 ~
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-12 ~
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-11 ~
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-10 ~
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-9 ~
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-8 ~
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-7 ~
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-6 ~
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-5 ~
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-4 ~
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-3 ~
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-2 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-1 ~

structure load mystructure:doomsday_expl ~ ~-68 ~-165
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-67 ~-165
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-66 ~-165
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-65 ~-165
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-64 ~-165
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-63 ~-165
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-62 ~-165
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-61 ~-165
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-60 ~-165
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-59 ~-165
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-58 ~-165
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-57 ~-165
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-56 ~-165
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-55 ~-165
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-54 ~-165
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-53 ~-165
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-52 ~-165
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-51 ~-165
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-50 ~-165
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-49 ~-165
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-48 ~-165
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-47 ~-165
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-46 ~-165
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-45 ~-165
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-44 ~-165
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-43 ~-165
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-42 ~-165
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-41 ~-165
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-40 ~-165
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-39 ~-165
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-38 ~-165
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-37 ~-165
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-36 ~-165
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-35 ~-165
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-34 ~-165
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-33 ~-165
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-32 ~-165
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-31 ~-165
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-30 ~-165
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-29 ~-165
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-28 ~-165
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-27 ~-165
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-26 ~-165
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-25 ~-165
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-24 ~-165
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-23 ~-165
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-22 ~-165
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-21 ~-165
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-20 ~-165
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-19 ~-165
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-18 ~-165
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-17 ~-165
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-16 ~-165
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-15 ~-165
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-14 ~-165
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-13 ~-165
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-12 ~-165
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-11 ~-165
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-10 ~-165
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-9 ~-165
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-8 ~-165
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-7 ~-165
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-6 ~-165
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-5 ~-165
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-4 ~-165
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-3 ~-165
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-2 ~-165
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-1 ~-165

structure load mystructure:doomsday_expl ~-161 ~-68 ~-165
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-67 ~-165
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-66 ~-165
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-65 ~-165
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-64 ~-165
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-63 ~-165
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-62 ~-165
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-61 ~-165
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-60 ~-165
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-59 ~-165
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-58 ~-165
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-57 ~-165
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-56 ~-165
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-55 ~-165
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-54 ~-165
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-53 ~-165
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-52 ~-165
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-51 ~-165
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-50 ~-165
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-49 ~-165
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-48 ~-165
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-47 ~-165
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-46 ~-165
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-45 ~-165
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-44 ~-165
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-43 ~-165
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-42 ~-165
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-41 ~-165
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-40 ~-165
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-39 ~-165
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-38 ~-165
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-37 ~-165
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-36 ~-165
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-35 ~-165
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-34 ~-165
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-33 ~-165
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-32 ~-165
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-31 ~-165
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-30 ~-165
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-29 ~-165
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-28 ~-165
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-27 ~-165
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-26 ~-165
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-25 ~-165
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-24 ~-165
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-23 ~-165
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-22 ~-165
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-21 ~-165
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-20 ~-165
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-19 ~-165
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-18 ~-165
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-17 ~-165
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-16 ~-165
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-15 ~-165
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-14 ~-165
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-13 ~-165
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-12 ~-165
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-11 ~-165
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-10 ~-165
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-9 ~-165
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-8 ~-165
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-7 ~-165
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-6 ~-165
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-5 ~-165
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-4 ~-165
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-3 ~-165
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-2 ~-165
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-1 ~-165

structure load mystructure:doomsday_expl ~-161 ~-68 ~
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-67 ~
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-66 ~
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-65 ~
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-64 ~
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-63 ~
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-62 ~
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-61 ~
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-60 ~
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-59 ~
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-58 ~
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-57 ~
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-56 ~
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-55 ~
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-54 ~
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-53 ~
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-52 ~
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-51 ~
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-50 ~
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-49 ~
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-48 ~
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-47 ~
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-46 ~
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-45 ~
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-44 ~
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-43 ~
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-42 ~
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-41 ~
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-40 ~
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-39 ~
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-38 ~
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-37 ~
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-36 ~
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-35 ~
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-34 ~
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-33 ~
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-32 ~
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-31 ~
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-30 ~
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-29 ~
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-28 ~
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-27 ~
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-26 ~
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-25 ~
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-24 ~
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-23 ~
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-22 ~
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-21 ~
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-20 ~
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-19 ~
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-18 ~
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-17 ~
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-16 ~
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-15 ~
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-14 ~
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-13 ~
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-12 ~
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-11 ~
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-10 ~
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-9 ~
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-8 ~
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-7 ~
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-6 ~
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-5 ~
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-4 ~
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-3 ~
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-2 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-1 ~

structure load mystructure:doomsday_expl ~-161 ~-68 ~-82
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-67 ~-82
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-66 ~-82
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-65 ~-82
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-64 ~-82
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-63 ~-82
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-62 ~-82
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-61 ~-82
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-60 ~-82
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-59 ~-82
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-58 ~-82
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-57 ~-82
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-56 ~-82
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-55 ~-82
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-54 ~-82
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-53 ~-82
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-52 ~-82
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-51 ~-82
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-50 ~-82
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-49 ~-82
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-48 ~-82
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-47 ~-82
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-46 ~-82
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-45 ~-82
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-44 ~-82
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-43 ~-82
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-42 ~-82
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-41 ~-82
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-40 ~-82
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-39 ~-82
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-38 ~-82
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-37 ~-82
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-36 ~-82
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-35 ~-82
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-34 ~-82
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-33 ~-82
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-32 ~-82
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-31 ~-82
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-30 ~-82
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-29 ~-82
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-28 ~-82
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-27 ~-82
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-26 ~-82
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-25 ~-82
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-24 ~-82
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-23 ~-82
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-22 ~-82
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-21 ~-82
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-20 ~-82
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-19 ~-82
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-18 ~-82
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-17 ~-82
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-16 ~-82
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-15 ~-82
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-14 ~-82
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-13 ~-82
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-12 ~-82
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-11 ~-82
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-10 ~-82
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-9 ~-82
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-8 ~-82
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-7 ~-82
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-6 ~-82
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-5 ~-82
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-4 ~-82
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-3 ~-82
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-2 ~-82
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~-161 ~-1 ~-82

structure load mystructure:doomsday_expl ~-81 ~-68 ~-165
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-67 ~-165
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-66 ~-165
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-65 ~-165
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-64 ~-165
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-63 ~-165
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-62 ~-165
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-61 ~-165
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-60 ~-165
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-59 ~-165
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-58 ~-165
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-57 ~-165
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-56 ~-165
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-55 ~-165
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-54 ~-165
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-53 ~-165
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-52 ~-165
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-51 ~-165
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-50 ~-165
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-49 ~-165
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-48 ~-165
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-47 ~-165
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-46 ~-165
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-45 ~-165
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-44 ~-165
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-43 ~-165
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-42 ~-165
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-41 ~-165
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-40 ~-165
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-39 ~-165
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-38 ~-165
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-37 ~-165
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-36 ~-165
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-35 ~-165
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-34 ~-165
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-33 ~-165
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-32 ~-165
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-31 ~-165
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-30 ~-165
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-29 ~-165
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-28 ~-165
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-27 ~-165
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-26 ~-165
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-25 ~-165
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-24 ~-165
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-23 ~-165
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-22 ~-165
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-21 ~-165
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-20 ~-165
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-19 ~-165
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-18 ~-165
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-17 ~-165
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-16 ~-165
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-15 ~-165
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-14 ~-165
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-13 ~-165
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-12 ~-165
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-11 ~-165
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-10 ~-165
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-9 ~-165
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-8 ~-165
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-7 ~-165
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-6 ~-165
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-5 ~-165
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-4 ~-165
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-3 ~-165
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-2 ~-165
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-1 ~-165

structure load mystructure:doomsday_expl ~-81 ~-68 ~
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-67 ~
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-66 ~
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-65 ~
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-64 ~
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-63 ~
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-62 ~
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-61 ~
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-60 ~
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-59 ~
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-58 ~
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-57 ~
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-56 ~
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-55 ~
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-54 ~
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-53 ~
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-52 ~
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-51 ~
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-50 ~
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-49 ~
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-48 ~
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-47 ~
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-46 ~
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-45 ~
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-44 ~
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-43 ~
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-42 ~
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-41 ~
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-40 ~
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-39 ~
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-38 ~
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-37 ~
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-36 ~
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-35 ~
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-34 ~
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-33 ~
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-32 ~
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-31 ~
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-30 ~
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-29 ~
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-28 ~
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-27 ~
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-26 ~
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-25 ~
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-24 ~
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-23 ~
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-22 ~
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-21 ~
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-20 ~
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-19 ~
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-18 ~
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-17 ~
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-16 ~
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-15 ~
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-14 ~
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-13 ~
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-12 ~
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-11 ~
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-10 ~
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-9 ~
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-8 ~
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-7 ~
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-6 ~
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-5 ~
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-4 ~
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-3 ~
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-2 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~-81 ~-1 ~

structure load mystructure:doomsday_expl ~ ~-68 ~-82
execute @s ~ ~ ~ detect ~ ~-67 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-67 ~-82
execute @s ~ ~ ~ detect ~ ~-66 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-66 ~-82
execute @s ~ ~ ~ detect ~ ~-65 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-65 ~-82
execute @s ~ ~ ~ detect ~ ~-64 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-64 ~-82
execute @s ~ ~ ~ detect ~ ~-63 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-63 ~-82
execute @s ~ ~ ~ detect ~ ~-62 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-62 ~-82
execute @s ~ ~ ~ detect ~ ~-61 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-61 ~-82
execute @s ~ ~ ~ detect ~ ~-60 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-60 ~-82
execute @s ~ ~ ~ detect ~ ~-59 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-59 ~-82
execute @s ~ ~ ~ detect ~ ~-58 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-58 ~-82
execute @s ~ ~ ~ detect ~ ~-57 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-57 ~-82
execute @s ~ ~ ~ detect ~ ~-56 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-56 ~-82
execute @s ~ ~ ~ detect ~ ~-55 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-55 ~-82
execute @s ~ ~ ~ detect ~ ~-54 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-54 ~-82
execute @s ~ ~ ~ detect ~ ~-53 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-53 ~-82
execute @s ~ ~ ~ detect ~ ~-52 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-52 ~-82
execute @s ~ ~ ~ detect ~ ~-51 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-51 ~-82
execute @s ~ ~ ~ detect ~ ~-50 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-50 ~-82
execute @s ~ ~ ~ detect ~ ~-49 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-49 ~-82
execute @s ~ ~ ~ detect ~ ~-48 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-48 ~-82
execute @s ~ ~ ~ detect ~ ~-47 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-47 ~-82
execute @s ~ ~ ~ detect ~ ~-46 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-46 ~-82
execute @s ~ ~ ~ detect ~ ~-45 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-45 ~-82
execute @s ~ ~ ~ detect ~ ~-44 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-44 ~-82
execute @s ~ ~ ~ detect ~ ~-43 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-43 ~-82
execute @s ~ ~ ~ detect ~ ~-42 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-42 ~-82
execute @s ~ ~ ~ detect ~ ~-41 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-41 ~-82
execute @s ~ ~ ~ detect ~ ~-40 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-40 ~-82
execute @s ~ ~ ~ detect ~ ~-39 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-39 ~-82
execute @s ~ ~ ~ detect ~ ~-38 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-38 ~-82
execute @s ~ ~ ~ detect ~ ~-37 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-37 ~-82
execute @s ~ ~ ~ detect ~ ~-36 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-36 ~-82
execute @s ~ ~ ~ detect ~ ~-35 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-35 ~-82
execute @s ~ ~ ~ detect ~ ~-34 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-34 ~-82
execute @s ~ ~ ~ detect ~ ~-33 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-33 ~-82
execute @s ~ ~ ~ detect ~ ~-32 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-32 ~-82
execute @s ~ ~ ~ detect ~ ~-31 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-31 ~-82
execute @s ~ ~ ~ detect ~ ~-30 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-30 ~-82
execute @s ~ ~ ~ detect ~ ~-29 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-29 ~-82
execute @s ~ ~ ~ detect ~ ~-28 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-28 ~-82
execute @s ~ ~ ~ detect ~ ~-27 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-27 ~-82
execute @s ~ ~ ~ detect ~ ~-26 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-26 ~-82
execute @s ~ ~ ~ detect ~ ~-25 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-25 ~-82
execute @s ~ ~ ~ detect ~ ~-24 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-24 ~-82
execute @s ~ ~ ~ detect ~ ~-23 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-23 ~-82
execute @s ~ ~ ~ detect ~ ~-22 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-22 ~-82
execute @s ~ ~ ~ detect ~ ~-21 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-21 ~-82
execute @s ~ ~ ~ detect ~ ~-20 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-20 ~-82
execute @s ~ ~ ~ detect ~ ~-19 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-19 ~-82
execute @s ~ ~ ~ detect ~ ~-18 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-18 ~-82
execute @s ~ ~ ~ detect ~ ~-17 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-17 ~-82
execute @s ~ ~ ~ detect ~ ~-16 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-16 ~-82
execute @s ~ ~ ~ detect ~ ~-15 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-15 ~-82
execute @s ~ ~ ~ detect ~ ~-14 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-14 ~-82
execute @s ~ ~ ~ detect ~ ~-13 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-13 ~-82
execute @s ~ ~ ~ detect ~ ~-12 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-12 ~-82
execute @s ~ ~ ~ detect ~ ~-11 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-11 ~-82
execute @s ~ ~ ~ detect ~ ~-10 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-10 ~-82
execute @s ~ ~ ~ detect ~ ~-9 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-9 ~-82
execute @s ~ ~ ~ detect ~ ~-8 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-8 ~-82
execute @s ~ ~ ~ detect ~ ~-7 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-7 ~-82
execute @s ~ ~ ~ detect ~ ~-6 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-6 ~-82
execute @s ~ ~ ~ detect ~ ~-5 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-5 ~-82
execute @s ~ ~ ~ detect ~ ~-4 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-4 ~-82
execute @s ~ ~ ~ detect ~ ~-3 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-3 ~-82
execute @s ~ ~ ~ detect ~ ~-2 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-2 ~-82
execute @s ~ ~ ~ detect ~ ~-1 ~ bedrock -1 structure load mystructure:doomsday_expl ~ ~-1 ~-82