structure delete mystructure:aether_house
structure delete mystructure:city_1
structure delete mystructure:city_2
structure delete mystructure:city_3
structure delete mystructure:city_4
structure delete mystructure:city_5
structure delete mystructure:city_6
structure delete mystructure:city_7
structure delete mystructure:city_8
structure delete mystructure:city_9
structure delete mystructure:doomsday_expl
structure delete mystructure:door_1
structure delete mystructure:door_2
structure delete mystructure:door_3
structure delete mystructure:door_4
structure delete mystructure:door_5
structure delete mystructure:door_6
structure delete mystructure:door_7
structure delete mystructure:door_8
structure delete mystructure:door_9
structure delete mystructure:door_10
structure delete mystructure:pillager_tower
structure delete mystructure:sleeping_man
structure delete mystructure:temple
structure delete mystructure:tnt
structure delete mystructure:village_house