summon sndbx:toxic_goo_block ~-9 ~ ~-1
summon sndbx:toxic_goo_block ~-8 ~ ~-9
summon sndbx:toxic_goo_block ~-7 ~ ~-2
summon sndbx:toxic_goo_block ~-5 ~ ~-6
summon sndbx:toxic_goo_block ~-2 ~ ~3
summon sndbx:toxic_goo_block ~-9 ~ ~1
summon sndbx:toxic_goo_block ~-10 ~ ~0
summon sndbx:toxic_goo_block ~-8 ~ ~-2
summon sndbx:toxic_goo_block ~-5 ~ ~1
summon sndbx:toxic_goo_block ~-8 ~ ~-1
summon sndbx:toxic_goo_block ~-6 ~ ~3
summon sndbx:toxic_goo_block ~-6 ~ ~-6
summon sndbx:toxic_goo_block ~-7 ~ ~-9
summon sndbx:toxic_goo_block ~-6 ~ ~0
summon sndbx:toxic_goo_block ~-8 ~ ~-5
summon sndbx:toxic_goo_block ~-1 ~ ~3
summon sndbx:toxic_goo_block ~-1 ~ ~-2
summon sndbx:toxic_goo_block ~-1 ~ ~1
summon sndbx:toxic_goo_block ~-6 ~ ~5
summon sndbx:toxic_goo_block ~-3 ~ ~0
summon sndbx:toxic_goo_block ~-4 ~ ~-1
summon sndbx:toxic_goo_block ~-7 ~ ~6
summon sndbx:toxic_goo_block ~1 ~ ~-9
summon sndbx:toxic_goo_block ~-4 ~ ~-7
summon sndbx:toxic_goo_block ~-8 ~ ~-7
summon sndbx:toxic_goo_block ~-2 ~ ~-2
summon sndbx:toxic_goo_block ~-3 ~ ~-1
summon sndbx:toxic_goo_block ~-3 ~ ~-2
summon sndbx:toxic_goo_block ~-4 ~ ~2
summon sndbx:toxic_goo_block ~-1 ~ ~-2
summon sndbx:toxic_goo_block ~-8 ~ ~-1
summon sndbx:toxic_goo_block ~-4 ~ ~6
summon sndbx:toxic_goo_block ~1 ~ ~0
summon sndbx:toxic_goo_block ~-4 ~ ~-9
summon sndbx:toxic_goo_block ~-7 ~ ~-6
summon sndbx:toxic_goo_block ~1 ~ ~-4
summon sndbx:toxic_goo_block ~-6 ~ ~-4
summon sndbx:toxic_goo_block ~-7 ~ ~1
summon sndbx:toxic_goo_block ~-3 ~ ~0
summon sndbx:toxic_goo_block ~-3 ~ ~3
summon sndbx:toxic_goo_block ~0 ~ ~5
summon sndbx:toxic_goo_block ~2 ~ ~-2
summon sndbx:toxic_goo_block ~-1 ~ ~5
summon sndbx:toxic_goo_block ~2 ~ ~8
summon sndbx:toxic_goo_block ~-3 ~ ~-4
summon sndbx:toxic_goo_block ~-4 ~ ~-5
summon sndbx:toxic_goo_block ~2 ~ ~-3
summon sndbx:toxic_goo_block ~-2 ~ ~1
summon sndbx:toxic_goo_block ~1 ~ ~-2
summon sndbx:toxic_goo_block ~-5 ~ ~-1
summon sndbx:toxic_goo_block ~-4 ~ ~1
summon sndbx:toxic_goo_block ~-5 ~ ~2
summon sndbx:toxic_goo_block ~2 ~ ~5
summon sndbx:toxic_goo_block ~2 ~ ~-1
summon sndbx:toxic_goo_block ~-2 ~ ~2
summon sndbx:toxic_goo_block ~4 ~ ~-5
summon sndbx:toxic_goo_block ~3 ~ ~-7
summon sndbx:toxic_goo_block ~4 ~ ~-7
summon sndbx:toxic_goo_block ~-2 ~ ~-2
summon sndbx:toxic_goo_block ~-1 ~ ~-5
summon sndbx:toxic_goo_block ~0 ~ ~-4
summon sndbx:toxic_goo_block ~-1 ~ ~-2
summon sndbx:toxic_goo_block ~-3 ~ ~-3
summon sndbx:toxic_goo_block ~4 ~ ~6
summon sndbx:toxic_goo_block ~-4 ~ ~2
summon sndbx:toxic_goo_block ~-1 ~ ~0
summon sndbx:toxic_goo_block ~3 ~ ~-3
summon sndbx:toxic_goo_block ~3 ~ ~-7
summon sndbx:toxic_goo_block ~5 ~ ~-5
summon sndbx:toxic_goo_block ~-4 ~ ~-7
summon sndbx:toxic_goo_block ~-2 ~ ~2
summon sndbx:toxic_goo_block ~3 ~ ~-2
summon sndbx:toxic_goo_block ~-3 ~ ~-1
summon sndbx:toxic_goo_block ~0 ~ ~5
summon sndbx:toxic_goo_block ~5 ~ ~2
summon sndbx:toxic_goo_block ~-2 ~ ~7
summon sndbx:toxic_goo_block ~0 ~ ~5
summon sndbx:toxic_goo_block ~1 ~ ~-3
summon sndbx:toxic_goo_block ~-3 ~ ~-3
summon sndbx:toxic_goo_block ~2 ~ ~-4
summon sndbx:toxic_goo_block ~2 ~ ~0
summon sndbx:toxic_goo_block ~-2 ~ ~-2
summon sndbx:toxic_goo_block ~4 ~ ~4
summon sndbx:toxic_goo_block ~0 ~ ~-2
summon sndbx:toxic_goo_block ~2 ~ ~-1
summon sndbx:toxic_goo_block ~2 ~ ~6
summon sndbx:toxic_goo_block ~4 ~ ~1
summon sndbx:toxic_goo_block ~1 ~ ~5
summon sndbx:toxic_goo_block ~4 ~ ~-5
summon sndbx:toxic_goo_block ~2 ~ ~-3
summon sndbx:toxic_goo_block ~7 ~ ~-4
summon sndbx:toxic_goo_block ~-1 ~ ~-2
summon sndbx:toxic_goo_block ~4 ~ ~-4
summon sndbx:toxic_goo_block ~-2 ~ ~-3
summon sndbx:toxic_goo_block ~6 ~ ~0
summon sndbx:toxic_goo_block ~2 ~ ~2
summon sndbx:toxic_goo_block ~5 ~ ~0
summon sndbx:toxic_goo_block ~2 ~ ~4
summon sndbx:toxic_goo_block ~-1 ~ ~4
summon sndbx:toxic_goo_block ~2 ~ ~-4